{"time":"2024-10-10T09:53:07.3733754+07:00","level":"INFO","msg":"using version","core version":"0.18.3"}
{"time":"2024-10-10T09:53:07.3733754+07:00","level":"INFO","msg":"created symlink","path":"X:\\Repositories\\PosStateFormer\\wandb\\run-20241010_095307-uwxlvb0q\\logs\\debug-core.log"}
{"time":"2024-10-10T09:53:07.606498+07:00","level":"ERROR","msg":"dialing: google: could not find default credentials. See https://cloud.google.com/docs/authentication/external/set-up-adc for more information"}
{"time":"2024-10-10T09:53:07.622213+07:00","level":"INFO","msg":"created new stream","id":"uwxlvb0q"}
{"time":"2024-10-10T09:53:07.622213+07:00","level":"INFO","msg":"stream: started","id":"uwxlvb0q"}
{"time":"2024-10-10T09:53:07.622213+07:00","level":"INFO","msg":"handler: started","stream_id":{"value":"uwxlvb0q"}}
{"time":"2024-10-10T09:53:07.6227423+07:00","level":"INFO","msg":"sender: started","stream_id":{"value":"uwxlvb0q"}}
{"time":"2024-10-10T09:53:07.6227423+07:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"uwxlvb0q"}}
{"time":"2024-10-10T09:53:08.968603+07:00","level":"INFO","msg":"wandb-core","!BADKEY":null}
{"time":"2024-10-10T09:53:08.9700166+07:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-10-10T09:55:06.1498036+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.1.153.161:57547->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-10-10T09:55:29.2076872+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/AiTA_HMER/hybridformer-mamba/uwxlvb0q/file_stream\": read tcp 10.1.153.161:57645->35.186.228.49:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"time":"2024-10-10T09:55:29.5191002+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
